version: "3.8"

volumes:
  blog-engine-database:
    name: ${BLOG_ENGINE_DB_CONTAINER_NAME}-${ENVIRONEMENT}

services:
  # DB
  blog-engine-database:
    container_name: ${BLOG_ENGINE_DB_CONTAINER_NAME}-${ENVIRONEMENT}
    image: postgres:latest

    restart: always

    environment:
      - POSTGRES_DB=${BLOG_ENGINE_DB_CATALOG}
      - POSTGRES_USER=${BLOG_ENGINE_DB_USER}
      - POSTGRES_PASSWORD=${BLOG_ENGINE_DB_PASSWORD}
      - POSTGRES_INITDB_ARGS="--data-checksums"

    ports:
      - ${BLOG_ENGINE_DB_PORT}:5432

    volumes:
      - blog-engine-database:/var/lib/postgresql/data

    networks:
      - blog-engine

  #API
  api:
    container_name: ${BLOG_ENGINE_API_CONTAINER_NAME}-${ENVIRONEMENT}
    image: blog/engine/api:${BLOG_ENGINE_API_VERSION}
    build:
      target: api
      context: ../
      dockerfile: ./docker/backend/Dockerfile

    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONEMENT}

    ports:
      - ${BLOG_ENGINE_API_PORT}:80

    volumes:
      - ../src/backend/Blog.Engine.Api/appsettings.json/:/app/appsettings.json:ro
      - ../src/backend/Blog.Engine.Api/appsettings.${ENVIRONEMENT}.json/:/app/appsettings.${ENVIRONEMENT}.json:ro

    networks:
      - blog-engine

    depends_on:
      - blog-engine-database
